Repository boostcampwm-2022/web17-waglewagle, pull requests merged in 2022-11, with the labels that each got.

#15 [Env] 환경설정 완료
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/tsconfig.json
Labels: 리뷰요청, env

#38 [Feat] 테스트 API 수신 확인
  frontend/components/common/ButtonLayout.tsx
  frontend/components/common/DefaultButton.tsx
  frontend/components/common/index.ts
  frontend/components/home/HomeHero.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/public/images/planet.png
  frontend/sass/components/common/DefaultButton.module.scss
Labels: 리뷰요청, feat

#51 [feat] username을 활용한 login 구현
  rest/src/main/java/com/waglewagle/rest/user/OauthMethod.java
  rest/src/main/java/com/waglewagle/rest/user/User.java
  rest/src/main/java/com/waglewagle/rest/user/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/UserRepository.java
  rest/src/main/java/com/waglewagle/rest/user/UserService.java
  rest/src/main/java/com/waglewagle/rest/user/dto/LoginResponseDTO.java
  rest/src/main/java/com/waglewagle/rest/user/dto/UsernameLoginDTO.java
  rest/src/main/resources/general.yml
  rest/src/test/java/com/waglewagle/rest/user/UserControllerTest.java
  rest/src/test/java/com/waglewagle/rest/user/UserRepositoryTest.java
Labels: feat

#63 [Feat] 커뮤니티 페이지 레이아웃
  frontend/components/community/AutoComplete.tsx
  frontend/components/community/CommunityHeader.tsx
  frontend/components/community/CommunityLayout.tsx
  frontend/components/community/index.ts
  frontend/components/main/MainHeader.tsx
  frontend/pages/community/[id].tsx
  frontend/public/images/add-circle.svg
  frontend/public/images/person.svg
  frontend/public/images/user.svg
  frontend/sass/components/community/AutoComplete.module.scss
  frontend/sass/components/community/CommunityHeader.module.scss
  frontend/sass/components/community/CommunityLayout.module.scss
  frontend/sass/components/main/CommunityList.module.scss
  frontend/sass/components/main/MainHeader.module.scss
  frontend/sass/components/main/MainLayout.module.scss
  frontend/tsconfig.json
  frontend/utils/SearchEngine.ts
  frontend/utils/TrieSearchEngine.ts
Labels: 리뷰요청, UI 디자인, 프론트엔드

#65 [feat] 키워드 참여 및 참여 취소 이벤트 대응 로직 작성
  socket/.gitignore
  socket/.idea/.gitignore
  socket/.idea/modules.xml
  socket/.idea/socket.iml
  socket/.idea/vcs.xml
  socket/package-lock.json
  socket/package.json
  socket/src/app.ts
  socket/src/config/env.ts
  socket/src/config/env.types.ts
  socket/src/config/orm-config.ts
  socket/src/controller/Keyword.Controller.ts
  socket/src/controller/controller.interface.ts
  socket/src/entity/Community.ts
  socket/src/entity/CommunityUser.ts
  socket/src/entity/Keyword.ts
  socket/src/entity/KeywordUser.ts
  socket/src/entity/Thread.ts
  socket/src/entity/User.ts
  socket/src/repository/Community.repository.ts
  socket/src/repository/CommunityUser.repository.ts
  socket/src/repository/Keyword.repository.ts
  socket/src/repository/KeywordUser.repository.ts
  socket/src/repository/data-source.ts
  socket/src/repository/repository.interface.ts
  socket/src/server.ts
  socket/src/service/Community.service.ts
  socket/src/service/CommunityUser.service.ts
  socket/src/service/Keyword.service.ts
  socket/src/service/KeywordUser.service.ts
  socket/src/types/socket.types.ts
  socket/src/utils/error-message.enum.ts
  socket/src/utils/error.ts
  socket/src/utils/event-input.types.ts
  socket/src/utils/event-response.types.ts
  socket/src/utils/event.enum.ts
  socket/src/utils/util.ts
  socket/tsconfig.json
Labels: feat, 백엔드

#76 [Fix] 선택된 키워드 기반, 연관 키워드 계산 API 알고리즘 수정(+ 커뮤니티 전체 키워드 리스트 API 구현)
  .idea/dataSources.xml
  .idea/waglewagle.iml
  rest/.gitignore
  rest/build.gradle
  rest/src/main/java/com/waglewagle/rest/community/CommunityRepository.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/config/DatabaseConfig.java
  rest/src/main/java/com/waglewagle/rest/keyword/Keyword.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordDTO.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/keyword/association/AssociationCalculator.java
  rest/src/main/java/com/waglewagle/rest/keyword/association/AssociationCalculatorConfig.java
  rest/src/main/java/com/waglewagle/rest/keyword/association/AssociationDTO.java
  rest/src/main/java/com/waglewagle/rest/keyword/association/CollaborativeFiltering.java
  rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
  rest/src/main/resources/general.yml
Labels: 백엔드, fix

#77 [Feat] REST 서버 github actions CI/CD 스트립트 작성
  .github/workflows/rest-cicd.yml
  .gitignore
Labels: feat, 백엔드

#69 [Feat] 버블 차트 레이아웃 구현
  frontend/components/community/AutoComplete.tsx
  frontend/components/community/KeywordAddModal.tsx
  frontend/components/community/KeywordBubble.tsx
  frontend/components/community/KeywordBubbleChart.tsx
  frontend/components/community/index.ts
  frontend/pages/community/[id].tsx
  frontend/sass/components/community/KeywordBubble.module.scss
  frontend/sass/components/community/KeywordBubbleChart.module.scss
  frontend/types/types.ts
Labels: 리뷰요청, feat, 키워드 자동완성, 프론트엔드
