Repository boostcampwm-2022/web17-waglewagle, pull requests merged in 2022-12, with the labels that each got.

#79 [feat] database mock data generator 추가.
  database_seed/.gitignore
  database_seed/.idea/.gitignore
  database_seed/.idea/modules.xml
  database_seed/.idea/socket.iml
  database_seed/.idea/vcs.xml
  database_seed/package-lock.json
  database_seed/package.json
  database_seed/src/config/env.ts
  database_seed/src/config/env.types.ts
  database_seed/src/config/orm-config.ts
  database_seed/src/entity/Community.ts
  database_seed/src/entity/CommunityUser.ts
  database_seed/src/entity/Keyword.ts
  database_seed/src/entity/KeywordUser.ts
  database_seed/src/entity/Thread.ts
  database_seed/src/entity/User.ts
  database_seed/src/repository/data-source.ts
  database_seed/src/repository/seeds.ts
  database_seed/src/seed/unique.ts
  database_seed/src/seed/unique.worker.ts
  database_seed/threads
  database_seed/tsconfig.json
  socket/src/app.ts
  socket/src/config/orm-config.ts
  socket/src/controller/Keyword.Controller.ts
  socket/src/controller/controller.interface.ts
  socket/src/repository/Community.repository.ts
  socket/src/repository/CommunityUser.repository.ts
  socket/src/repository/Keyword.repository.ts
  socket/src/repository/KeywordUser.repository.ts
  socket/src/repository/repository.interface.ts
  socket/src/server.ts
  socket/src/service/Community.service.ts
  socket/src/service/CommunityUser.service.ts
  socket/src/service/Keyword.service.ts
  socket/src/service/KeywordUser.service.ts
  socket/src/types/socket.types.ts
  socket/src/utils/error-message.enum.ts
  socket/src/utils/error.ts
  socket/src/utils/event-input.types.ts
  socket/src/utils/event-response.types.ts
  socket/src/utils/event.enum.ts
  socket/src/utils/util.ts
Labels: feat, 백엔드

#106 [Feat] 로그인 모달창 api 연결 및 모달창 UI 수정
  frontend/components/common/LoginModalContent.tsx
  frontend/components/common/StartButton.tsx
  frontend/components/community/CommunityLayout.tsx
  frontend/components/home/HomeHero.tsx
  frontend/pages/community/[id].tsx
  frontend/sass/components/common/LoginModalContent.module.scss
  frontend/sass/components/community/CommunityHeader.module.scss
  frontend/sass/components/community/CommunityLayout.module.scss
  frontend/sass/components/community/KeywordBubbleChart.module.scss
  frontend/sass/globals.scss
Labels: bug, 리뷰요청, feat, 프론트엔드, fix

#113 [Feat] 스레드 모달 UI 작업
  frontend/components/community/keyword/CommentForm.tsx
  frontend/components/community/keyword/KeywordLayout.tsx
  frontend/components/community/keyword/KeywordMain.tsx
  frontend/components/community/keyword/KeywordModalContent.tsx
  frontend/components/community/keyword/KeywordUserList.tsx
  frontend/components/community/keyword/Sidebar.tsx
  frontend/components/community/keyword/Thread.tsx
  frontend/components/community/keyword/ThreadForm.tsx
  frontend/components/community/keyword/ThreadList.tsx
  frontend/components/community/keyword/index.ts
  frontend/public/images/close.svg
  frontend/public/images/comment.svg
  frontend/public/images/delete.svg
  frontend/sass/components/community/keyword/CommentForm.module.scss
  frontend/sass/components/community/keyword/KeywordLayout.module.scss
  frontend/sass/components/community/keyword/KeywordMain.module.scss
  frontend/sass/components/community/keyword/KeywordUserList.module.scss
  frontend/sass/components/community/keyword/Sidebar.module.scss
  frontend/sass/components/community/keyword/Thread.module.scss
  frontend/sass/components/community/keyword/ThreadForm.module.scss
  frontend/sass/components/community/keyword/ThreadList.module.scss
  frontend/types/types.ts
  frontend/utils/calculateTimeGap.ts
Labels: feat, UI 디자인, 프론트엔드

#117 [feat] 커뮤니티 가입 및 가입 커뮤니티 조회 기능
  rest/src/main/java/com/waglewagle/rest/community/CommunityController.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityDTO.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityRepository.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserRepository.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
Labels: feat, 백엔드

#128 [Feat] GET 'user/me' API 반환값 수정
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserRepository.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/user/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/UserService.java
  rest/src/main/java/com/waglewagle/rest/user/dto/UserInfoDTO.java
Labels: feat, 백엔드

#130 [Feat] 스레드 생성/삭제 API POST '/api/v1/thread', DELETE '/api/v1/thread' 구현
  rest/src/main/java/com/waglewagle/rest/thread/Thread.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadDTO.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadRepository.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/user/dto/AuthorDTO.java
Labels: feat, 백엔드

#134 [feat] 커뮤니티 최초 가입 컬럼 및 변경 API, 커뮤니티 프로필 변경 API 추가
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
Labels: feat, 백엔드

#143 [feat] 키워드 내 전체 스레드 조회 API
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/thread/Thread.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadDTO.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadRepository.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
Labels: feat, 백엔드, fix

#146 [feat] 유저 최근 활동 시간 컬럼 및 api 추가
  rest/src/main/java/com/waglewagle/rest/user/User.java
  rest/src/main/java/com/waglewagle/rest/user/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/UserRepository.java
  rest/src/main/java/com/waglewagle/rest/user/UserService.java
  rest/src/main/java/com/waglewagle/rest/user/dto/UserConnectionStatusDTO.java
Labels: feat, 백엔드

#147 [feat] oauth user entity에 last_activity 필드 추가
  oauth/package.json
  oauth/src/domain/oauth/oauth.service.ts
  oauth/src/domain/oauth/user.entity.ts
  oauth/src/domain/oauth/user.repository.ts
  oauth/src/enum/roll.enum.ts
  oauth/src/util/utils.ts
Labels: feat, 백엔드

#189 [Fix] 개발환경에서 인증서버 실행할 수 있도록 구현
  oauth/.prettierrc
  oauth/package-lock.json
  oauth/package.json
  oauth/src/conf/env.ts
Labels: :bug: bug, :sos: 리뷰요청, :file_folder: 백엔드, :wrench: fix, :signal_strength: 서버 통신

#191 [Fix] Week04 release Hotfix
  frontend/components/common/StartButton.tsx
  frontend/config.ts
Labels: :bug: bug, :computer: 프론트엔드, :wrench: fix

#199 [Feat] 키워드 그룹 모달 API 연동부분 유저 인증 관련 기능 추가 구현
  frontend/components/community/KeywordBubble.tsx
  frontend/components/community/KeywordBubbleChart.tsx
  frontend/components/community/keyword-group/CommentForm.tsx
  frontend/components/community/keyword-group/KeywordGroupMain.tsx
  frontend/components/community/keyword-group/KeywordGroupModalContent.tsx
  frontend/components/community/keyword-group/KeywordGroupSidebar.tsx
  frontend/components/community/keyword-group/KeywordGroupUserList.tsx
  frontend/components/community/keyword-group/Thread.tsx
  frontend/components/community/keyword-group/ThreadForm.tsx
  frontend/components/community/keyword-group/ThreadList.tsx
  frontend/hooks/useUserMe.tsx
  frontend/next.config.js
  frontend/sass/components/community/keyword/KeywordUserList.module.scss
  frontend/sass/components/community/keyword/Sidebar.module.scss
  frontend/types/types.ts
Labels: :sparkle: feat, :computer: 프론트엔드

#205 [Feat] KeywordAdder 컴포넌트 역할 분리, 키워드 추가 / 입장/ 삭제 useMuation으로 구현
  frontend/apis/apis.ts
  frontend/components/community/KeywordAddModal.tsx
  frontend/components/community/KeywordAddModalContent.tsx
  frontend/components/community/KeywordAdder.tsx
  frontend/components/community/KeywordAssociated.tsx
  frontend/components/community/KeywordBubbleChart.tsx
  frontend/components/community/MyKeyword.tsx
  frontend/components/community/MyKeywordList.tsx
  frontend/components/community/index.ts
  frontend/constants/constants.ts
  frontend/hooks/useAddKeywordMutation.tsx
  frontend/hooks/useDisjoinKeywordMutation.tsx
  frontend/hooks/useJoinKeywordMutation.tsx
  frontend/hooks/useMyKeywordQuery.tsx
  frontend/hooks/useRelatedKeywordList.tsx
  frontend/hooks/useUserKeywordList.tsx
  frontend/hooks/useUserMe.tsx
  frontend/pages/community/[id].tsx
  frontend/sass/components/community/MyKeywordList.module.scss
  frontend/types/types.ts
  frontend/utils/checkIsExistKeyword.ts
Labels: :bug: bug, :sparkle: feat, :abcd: 키워드 시각화, :computer: 프론트엔드, :recycle: refactor, :wrench: fix

#203 [Test] /user/me API 실패 테스트 작성 및 리팩토링
  rest/.gitignore
  rest/src/main/java/com/waglewagle/rest/common/PreResponseDTO.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityController.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityDTO.java
  rest/src/main/java/com/waglewagle/rest/community/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/community/repository/CommunityCustomRepository.java
  rest/src/main/java/com/waglewagle/rest/community/repository/CommunityCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/community/repository/CommunityRepository.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java
  rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
  rest/src/main/java/com/waglewagle/rest/communityUser/repository/CommunityUserCustomRepository.java
  rest/src/main/java/com/waglewagle/rest/communityUser/repository/CommunityUserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/communityUser/repository/CommunityUserRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/keywordUser/KeywordUserService.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/user/User.java
  rest/src/main/java/com/waglewagle/rest/user/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/UserService.java
  rest/src/main/java/com/waglewagle/rest/user/dto/UserConnectionStatusDTO.java
  rest/src/main/java/com/waglewagle/rest/user/repository/UserCustomRepository.java
  rest/src/main/java/com/waglewagle/rest/user/repository/UserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/user/repository/UserRepository.java
  rest/src/main/resources/application.yml
  rest/src/test/java/com/waglewagle/rest/user/UserControllerTest.java
  rest/src/test/java/com/waglewagle/rest/user/UserRepositoryTest.java
  rest/src/test/resources/secret.yml
Labels: :test_tube: test, :file_folder: 백엔드

#212 [Feat] 사이드바 스레드 정보 스레드 아이디 통해서 받아오도록 변경
  frontend/components/community/keyword-group/CommentForm.tsx
  frontend/components/community/keyword-group/KeywordGroupMain.tsx
  frontend/components/community/keyword-group/KeywordGroupSidebar.tsx
  frontend/components/community/keyword-group/Thread.tsx
  frontend/components/community/keyword-group/ThreadList.tsx
  frontend/hooks/useThreadListQuery.tsx
  frontend/utils/calculateTimeGap.ts
Labels: :sweat_drops: enhancement, :sparkle: feat, :computer: 프론트엔드

#218 [Fix] 키워드 가입 API, POST keyword/join, 중복가입 해결
  rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordUserRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
Labels: :file_folder: 백엔드, :wrench: fix

#219 [Feat] 커뮤니티 가입 구현
  frontend/apis/apis.ts
  frontend/components/community/KeywordAddModalContent.tsx
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/CommunityList.tsx
  frontend/constants/constants.ts
  frontend/hooks/useMockUserMe.tsx
  frontend/hooks/useUserCommunityQuery.tsx
  frontend/hooks/useUserMe.tsx
  frontend/pages/community/[id].tsx
  frontend/pages/index.tsx
  frontend/pages/main.tsx
  frontend/public/images/boostcamp.png
  frontend/public/images/default-profile.png
  frontend/sass/components/community/keyword/KeywordMain.module.scss
  frontend/sass/components/main/CommunityItem.module.scss
  frontend/sass/globals.scss
  frontend/types/types.ts
Labels: :sparkle: feat, :computer: 프론트엔드

#221 [refactor] User domain 휘하 DTO Request 및 Response 분류
  rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/ThreadDTO.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/request/ThreadRequest.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/response/ThreadResponse.java
  rest/src/main/java/com/waglewagle/rest/thread/dto/request/threadRequest.java
  rest/src/main/java/com/waglewagle/rest/thread/dto/response/threadResponse.java
  rest/src/main/java/com/waglewagle/rest/thread/entity/Thread.java
  rest/src/main/java/com/waglewagle/rest/user/controller/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/AuthorDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/LoginResponseDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/ProfileDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/UpdateProfileDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/UpdateProfileResponseDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/UserConnectionStatusDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/UserInfoDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/UsernameLoginDTO.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/request/UserRequest.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/request/userRequest.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/response/UserResponse.java
  rest/src/main/java/com/waglewagle/rest/user/data_object/dto/response/userResponse.java
  rest/src/main/java/com/waglewagle/rest/user/entity/User.java
  rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
  rest/src/test/java/com/waglewagle/rest/thread/ThreadServiceTest.java
Labels: :file_folder: 백엔드, :recycle: refactor

#222 [refactor] Thread 도메인 휘하 DTO Request 및 Response 분류
  rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/ThreadDTO.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/request/ThreadRequest.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/response/ThreadResponse.java
  rest/src/main/java/com/waglewagle/rest/thread/entity/Thread.java
  rest/src/main/java/com/waglewagle/rest/thread/repository/custom/ThreadCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/user/repository/custom/UserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
  rest/src/test/java/com/waglewagle/rest/thread/ThreadServiceTest.java
Labels: :file_folder: 백엔드, :recycle: refactor

#237 [refactor] keyword 도메인 산하 DTO request response vo로 분리
  rest/src/main/java/com/waglewagle/rest/keyword/controller/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/KeywordVO.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/dto/AssociationDTO.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/dto/KeywordDTO.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/dto/request/KeywordRequest.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/dto/response/KeywordResponse.java
  rest/src/main/java/com/waglewagle/rest/keyword/entity/Keyword.java
  rest/src/main/java/com/waglewagle/rest/keyword/entity/KeywordUser.java
  rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordUserService.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/association/AssociationCalculator.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/association/CollaborativeFiltering.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/association/DumbAssociateCalculator.java
Labels: :file_folder: 백엔드, :recycle: refactor

#236 [refactor] Community 도메인 휘하 DTO 분류 및 전반적인 스타일
  rest/src/main/java/com/waglewagle/rest/community/controller/CommunityController.java
  rest/src/main/java/com/waglewagle/rest/community/controller/CommunityUserController.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/CommunityDTO.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/CommunityUserDTO.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/request/CommunityRequest.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/request/CommunityUserRequest.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/response/CommunityResponse.java
  rest/src/main/java/com/waglewagle/rest/community/data_object/dto/response/CommunityUserResponse.java
  rest/src/main/java/com/waglewagle/rest/community/entity/Community.java
  rest/src/main/java/com/waglewagle/rest/community/entity/CommunityUser.java
  rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityUserService.java
Labels: :file_folder: 백엔드, :recycle: refactor

#238 [Feat] 전역 ExceptionHandler 구현(+예시 하나)
  rest/src/main/java/com/waglewagle/rest/common/error/GlobalExceptionHandler.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/NoSuchKeywordException.java
Labels: :sparkle: feat, :file_folder: 백엔드

#239 [refactor] validation 로직을 controller에서 service로 이동, Optional 사용 증가
  rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepository.java
  rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityUserService.java
  rest/src/main/java/com/waglewagle/rest/keyword/controller/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordRepository.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordUserService.java
  rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/request/ThreadRequest.java
  rest/src/main/java/com/waglewagle/rest/thread/repository/custom/ThreadCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/user/controller/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/entity/User.java
  rest/src/main/java/com/waglewagle/rest/user/repository/custom/UserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
  rest/src/test/java/com/waglewagle/rest/thread/ThreadServiceTest.java
Labels: :file_folder: 백엔드, :recycle: refactor

#241 [refactor] validation 로직 이동 및 exception을 throw하는 방식으로 변경
  rest/src/main/java/com/waglewagle/rest/common/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/common/exception/InvalidInputException.java
  rest/src/main/java/com/waglewagle/rest/community/controller/CommunityUserController.java
  rest/src/main/java/com/waglewagle/rest/community/exception/AlreadyJoinedCommunityException.java
  rest/src/main/java/com/waglewagle/rest/community/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/community/exception/NoSuchCommunityException.java
  rest/src/main/java/com/waglewagle/rest/community/exception/UnSubscribedCommunityException.java
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityUserService.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/AlreadyJoinedKeywordException.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
  rest/src/main/java/com/waglewagle/rest/thread/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/thread/exception/InvalidThreadException.java
  rest/src/main/java/com/waglewagle/rest/thread/exception/NoSuchThreadException.java
  rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
  rest/src/main/java/com/waglewagle/rest/user/controller/UserController.java
  rest/src/main/java/com/waglewagle/rest/user/exception/DuplicatedUsernameException.java
  rest/src/main/java/com/waglewagle/rest/user/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/user/exception/NoSuchUserException.java
  rest/src/main/java/com/waglewagle/rest/user/exception/UnauthorizedException.java
  rest/src/main/java/com/waglewagle/rest/user/repository/custom/UserCustomRepositoryImpl.java
  rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
  rest/src/main/resources/logback-spring.xml
Labels: :sparkle: feat, :file_folder: 백엔드, :recycle: refactor

#235 [Refactor] API 함수 모듈 분리 및 스레드 관련 훅 리팩토링
  frontend/apis/apis.ts
  frontend/apis/index.ts
  frontend/apis/instance.ts
  frontend/apis/keyword.ts
  frontend/apis/thread.ts
  frontend/components/admin/KeywordControl.tsx
  frontend/components/admin/KeywordDeleteModalContent.tsx
  frontend/components/admin/KeywordMergeModalContent.tsx
  frontend/components/community/KeywordGroupEnterModalContent.tsx
  frontend/components/community/keyword-group/CommentForm.tsx
  frontend/components/community/keyword-group/KeywordGroupMain.tsx
  frontend/components/community/keyword-group/KeywordGroupSidebar.tsx
  frontend/components/community/keyword-group/Thread.tsx
  frontend/components/community/keyword-group/ThreadForm.tsx
  frontend/components/community/keyword-group/ThreadList.tsx
  frontend/hooks/thread/useAddCommentMutation.tsx
  frontend/hooks/thread/useAddThreadMutation.tsx
  frontend/hooks/thread/useDeleteThreadMutation.tsx
  frontend/hooks/thread/useThreadListQuery.tsx
  frontend/hooks/useAddKeywordMutation.tsx
  frontend/hooks/useDisjoinKeywordMutation.tsx
  frontend/hooks/useJoinKeywordMutation.tsx
  frontend/hooks/useKeywordListQuery.tsx
  frontend/hooks/useKeywordUserListQuery.tsx
  frontend/hooks/useMyKeywordQuery.tsx
  frontend/hooks/useRelatedKeywordList.tsx
  frontend/hooks/useUserKeywordList.tsx
  frontend/sass/components/admin/keywordControl.module.scss
  frontend/tsconfig.json
Labels: :sweat_drops: enhancement, :computer: 프론트엔드

#245 [Refactor] API 관련 훅 디렉토리 분리, release 작업 내역 머지
  frontend/.eslintrc.json
  frontend/components/admin/KeywordControl.tsx
  frontend/components/admin/KeywordDeleteModalContent.tsx
  frontend/components/admin/KeywordMergeModalContent.tsx
  frontend/components/admin/UserControl.tsx
  frontend/components/common/MouseModal.tsx
  frontend/components/community/KeywordAddModalContent.tsx
  frontend/components/community/KeywordAdder.tsx
  frontend/components/community/KeywordAssociated.tsx
  frontend/components/community/KeywordBubbleChart.tsx
  frontend/components/community/KeywordGroupEnterModalContent.tsx
  frontend/components/community/KeywordGroupInfoModalContent.tsx
  frontend/components/community/MyKeyword.tsx
  frontend/components/community/MyKeywordList.tsx
  frontend/components/community/keyword-group/CommentForm.tsx
  frontend/components/community/keyword-group/KeywordGroupMain.tsx
  frontend/components/community/keyword-group/KeywordGroupSidebar.tsx
  frontend/components/community/keyword-group/KeywordGroupUserList.tsx
  frontend/components/community/keyword-group/Thread.tsx
  frontend/components/community/keyword-group/ThreadForm.tsx
  frontend/components/community/keyword-group/ThreadList.tsx
  frontend/hooks/keyword/index.ts
  frontend/hooks/keyword/useAddKeywordMutation.tsx
  frontend/hooks/keyword/useDisjoinKeywordMutation.tsx
  frontend/hooks/keyword/useJoinKeywordMutation.tsx
  frontend/hooks/keyword/useKeywordListQuery.tsx
  frontend/hooks/keyword/useKeywordUserListQuery.tsx
  frontend/hooks/keyword/useMyKeywordQuery.tsx
  frontend/hooks/keyword/useRelatedKeywordList.tsx
  frontend/hooks/thread/index.ts
Labels: :sweat_drops: enhancement, :computer: 프론트엔드

#246 [Enhancement] 키워드 모달 컴포넌트 접근성 개선
  frontend/components/community/KeywordAdder.tsx
  frontend/sass/components/admin/KeywordControl.module.scss
  frontend/sass/components/admin/KeywordMergeModalContent.module.scss
  frontend/sass/components/community/AutoCompleteFormLayout.module.scss
Labels: :sweat_drops: enhancement, :abcd: 키워드 시각화, :computer: 프론트엔드

#251 [Fix] 유저 피드백을 통한 버그 수정
  frontend/apis/apis.ts
  frontend/components/community/KeywordBubble.tsx
  frontend/components/community/KeywordGroupInfoModalContent.tsx
  frontend/components/community/keyword-group/KeywordGroupModalContent.tsx
  frontend/components/community/keyword-group/KeywordGroupUserList.tsx
  frontend/pages/community/[id].tsx
  frontend/pages/main.tsx
Labels: :computer: 프론트엔드, :wrench: fix

#250 [feat] ThreadService 테스트 코드 작성
  rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/ThreadVO.java
  rest/src/main/java/com/waglewagle/rest/thread/entity/Thread.java
  rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
  rest/src/test/java/com/waglewagle/rest/thread/ThreadServiceTest.java
  rest/src/test/java/com/waglewagle/rest/thread/service/ThreadServiceTest.java
Labels: :test_tube: test, :file_folder: 백엔드

#253 Be/feature/refactor/keyword/validation
  rest/src/main/java/com/waglewagle/rest/community/service/CommunityService.java
  rest/src/main/java/com/waglewagle/rest/keyword/controller/KeywordController.java
  rest/src/main/java/com/waglewagle/rest/keyword/data_object/dto/request/KeywordRequest.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/DuplicatedKeywordException.java
  rest/src/main/java/com/waglewagle/rest/keyword/exception/ExceptionMessage.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordUserService.java
  rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
Labels: :file_folder: 백엔드, :recycle: refactor

#261 [fix] 쓰레드 생성 API 버그 수정
  rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
Labels: :bug: bug, :file_folder: 백엔드, :wrench: fix

#264 [hotfix] validation 로직이 거꾸로 되어 에러가 발생하던 문제 해결
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
Labels: :bug: bug, :file_folder: 백엔드, :wrench: fix

#265 [fix] 키워드 머지 관련 권한 검증 로직 수정
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
Labels: :bug: bug, :file_folder: 백엔드, :wrench: fix

#266 [Feat] Parallax 스크롤 애니메이션
  frontend/components/home/HomeDescription.tsx
  frontend/hooks/useScrollChangeColor.tsx
  frontend/hooks/useScrollChangeOpacity.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/parallax/drawing-man.png
  frontend/public/images/parallax/friendly.png
  frontend/public/images/parallax/thinking.png
  frontend/sass/components/home/HomeDescription.module.scss
Labels: :sparkle: feat, :computer: 프론트엔드

#276 [Chore] Week06 Day01 간단한 일들
  frontend/components/community/CommunityHeader.tsx
  frontend/components/community/CommunityLayout.tsx
  frontend/components/community/MainKeywordAdderLayout.tsx
  frontend/components/community/MyKeywordHighlight.tsx
  frontend/components/community/index.ts
  frontend/components/community/keyword-add-modal/KeywordAddModalContent.tsx
  frontend/components/community/keyword-add-modal/KeywordAssociated.tsx
  frontend/components/community/keyword-add-modal/MyKeyword.tsx
  frontend/components/community/keyword-add-modal/MyKeywordList.tsx
  frontend/components/community/keyword-add-modal/index.ts
  frontend/components/community/keyword-adder/AutoCompleteFormLayout.tsx
  frontend/components/community/keyword-adder/KeywordAdder.tsx
  frontend/components/community/keyword-adder/SearchResultListLayout.tsx
  frontend/components/community/keyword-adder/index.ts
  frontend/components/community/keyword-bubble-chart/KeywordBubble.tsx
  frontend/components/community/keyword-bubble-chart/KeywordBubbleChart.tsx
  frontend/components/community/keyword-bubble-chart/KeywordGroupEnterModalContent.tsx
  frontend/components/community/keyword-bubble-chart/KeywordGroupInfoModalContent.tsx
  frontend/components/community/keyword-bubble-chart/index.ts
  frontend/pages/community/[id].tsx
  frontend/utils/debounce.ts
Labels: :computer: 프론트엔드

#279 [Refactor] 공통 스타일 분리
  frontend/sass/animations.scss
  frontend/sass/components/admin/UserControl.module.scss
  frontend/sass/components/common/LoginModalContent.module.scss
  frontend/sass/components/common/Modal.module.scss
  frontend/sass/components/common/MouseModal.module.scss
  frontend/sass/components/community/CommunityHeader.module.scss
  frontend/sass/components/community/keyword-add-modal/EnterButton.module.scss
  frontend/sass/components/community/keyword-add-modal/KeywordAddModalContent.module.scss
  frontend/sass/components/community/keyword-add-modal/MyKeyword.module.scss
  frontend/sass/components/community/keyword-add-modal/MyKeywordList.module.scss
  frontend/sass/components/community/keyword-adder/AutoCompleteFormLayout.module.scss
  frontend/sass/components/community/keyword-adder/KeywordAdderLayout.module.scss
  frontend/sass/components/home/HomeDescription.module.scss
  frontend/sass/components/home/HomeHero.module.scss
  frontend/sass/components/main/CommunityItem.module.scss
  frontend/sass/components/main/DefaultProfile.module.scss
  frontend/sass/components/main/MainHeader.module.scss
  frontend/sass/mixins.scss
Labels: :computer: 프론트엔드, :recycle: refactor

#282 [Fix] 키워드 목록 멤버수 정렬
  frontend/hooks/keyword/useKeywordListQuery.tsx
  frontend/sass/components/community/CommunityKeywordList.module.scss
Labels: :bug: bug, :wrench: fix

#288 [Refactor] 키워드 관련 API와 관리자 페이지 예외처리
  frontend/hooks/keyword/useAddKeywordMutation.tsx
  frontend/hooks/keyword/useDisjoinKeywordMutation.tsx
  frontend/hooks/keyword/useJoinKeywordMutation.tsx
  frontend/hooks/keyword/useKeywordListQuery.tsx
  frontend/hooks/keyword/useKeywordUserListQuery.tsx
  frontend/hooks/keyword/useMyKeywordQuery.tsx
  frontend/hooks/keyword/useRelatedKeywordList.tsx
  frontend/pages/admin/[id].tsx
  frontend/pages/community/[id].tsx
  frontend/pages/index.tsx
  frontend/pages/main.tsx
  frontend/sass/components/community/CommunityKeywordList.module.scss
  frontend/types/types.ts
Labels: :bug: bug, :computer: 프론트엔드, :recycle: refactor, :wrench: fix, :gear: 관리자 기능

#292 [Feat] Week06 Day02 코드 품질 개선
  frontend/hooks/keyword/useRelatedKeywordList.tsx
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/community/[id].tsx
  frontend/sass/components/community/CommunityKeywordList.module.scss
  frontend/sass/components/community/keyword-add-modal/MyKeywordList.module.scss
  frontend/utils/searchEngine/TrieSearchEngine.test.ts
  frontend/utils/searchEngine/TrieSearchEngine.ts
Labels: :sweat_drops: enhancement, :sparkle: feat, :test_tube: test, :computer: 프론트엔드, :wrench: fix

#293 [fix] 키워드가 존재하지 않아도 생성할 수 없던 버그 수정
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
Labels: :file_folder: 백엔드, :wrench: fix

#316 [Feat] 서버 테스트 스크립트 작성
  artillery/.gitignore
  artillery/README.md
  artillery/test/artillery.yml
  artillery/test/forPresent.yml
  artillery/test/main.yml
  artillery/test/polling.yml
  rest/.gitignore
Labels: :sparkle: feat, :test_tube: test, :file_folder: 백엔드

#317 [feat] keywordService 테스트 코드 추가
  rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
  rest/src/test/java/com/waglewagle/rest/keyword/service/KeywordServiceTest.java
Labels: :test_tube: test, :file_folder: 백엔드

#319 [Fix] 첫 로그인 시, 부캠 커뮤니티 가입
  frontend/.eslintrc.json
  frontend/hooks/useJoinBoostcampCommunity.tsx
  frontend/package-lock.json
  frontend/pages/community/[id].tsx
  frontend/pages/index.tsx
  frontend/pages/main.tsx
Labels: :bug: bug, :wrench: fix

#340 [Chore] 스타일 수정
  frontend/apis/user.ts
  frontend/components/admin/AdminMain.tsx
  frontend/components/admin/UserControl.tsx
  frontend/components/community/CommunityHeader.tsx
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/MainTitle.tsx
  frontend/pages/admin/[id].tsx
  frontend/sass/components/admin/AdminMain.module.scss
  frontend/sass/components/admin/AdminSidebar.module.scss
  frontend/sass/components/admin/KeywordControl.module.scss
  frontend/sass/components/common/DefaultButton.module.scss
  frontend/sass/components/common/LoginModalContent.module.scss
  frontend/sass/components/community/keyword-bubble-chart/KeywordBubble.module.scss
  frontend/sass/components/main/CommunityItem.module.scss
  frontend/sass/components/main/MainLayout.module.scss
Labels: :sweat_drops: enhancement, :art: UI 디자인, :computer: 프론트엔드

#344 [Fix] Week07 Day01 버그 수정 (공백 게시글 작성 버그, 키워드 입장 모달 잘리는 버그, 기본 프로필 이미지)
  frontend/components/common/MouseModal.tsx
  frontend/components/community/keyword-bubble-chart/KeywordBubble.tsx
  frontend/components/main/DefaultProfile.tsx
  frontend/pages/community/[id].tsx
  frontend/utils/isEmptyInput.ts
Labels: :bug: bug, :abcd: 키워드 시각화, :computer: 프론트엔드, :wrench: fix

#345 [Week07 Day01] 버그 수정 배포
  frontend/apis/user.ts
  frontend/components/admin/AdminMain.tsx
  frontend/components/admin/UserControl.tsx
  frontend/components/common/MouseModal.tsx
  frontend/components/community/CommunityHeader.tsx
  frontend/components/community/keyword-bubble-chart/KeywordBubble.tsx
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/DefaultProfile.tsx
  frontend/components/main/MainTitle.tsx
  frontend/pages/admin/[id].tsx
  frontend/pages/community/[id].tsx
  frontend/sass/components/admin/AdminMain.module.scss
  frontend/sass/components/admin/AdminSidebar.module.scss
  frontend/sass/components/admin/KeywordControl.module.scss
  frontend/sass/components/common/DefaultButton.module.scss
  frontend/sass/components/common/LoginModalContent.module.scss
  frontend/sass/components/community/keyword-bubble-chart/KeywordBubble.module.scss
  frontend/sass/components/main/CommunityItem.module.scss
  frontend/sass/components/main/MainLayout.module.scss
  frontend/utils/isEmptyInput.ts
Labels: :bug: bug, :computer: 프론트엔드, :wrench: fix

#349 [Feat] 메인 페이지 커뮤니티 유저 수 표시
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/CommunityList.tsx
  frontend/types/types.ts
Labels: :sparkle: feat, :computer: 프론트엔드

#350 [Document] 삭제된 이슈 템플릿, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/-documeent-.md
  .github/ISSUE_TEMPLATE/-enhancement-.md
  .github/ISSUE_TEMPLATE/-feat-.md
  .github/ISSUE_TEMPLATE/-fix-.md
  .github/ISSUE_TEMPLATE/-refactor-.md
  .github/ISSUE_TEMPLATE/-test-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :bug: bug, :page_facing_up: documentation, :wrench: fix

#351 [Env] fe/main 브랜치 cd 스크립트
  .github/workflows/frontend-main-cd.yml
  .github/workflows/frontend-release-cd.yml
Labels: :recycle: env, :computer: 프론트엔드

#347 [Week07 Day01] 배포 확인 완료
  frontend/apis/user.ts
  frontend/components/admin/AdminMain.tsx
  frontend/components/admin/UserControl.tsx
  frontend/components/common/MouseModal.tsx
  frontend/components/community/CommunityHeader.tsx
  frontend/components/community/keyword-bubble-chart/KeywordBubble.tsx
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/DefaultProfile.tsx
  frontend/components/main/MainTitle.tsx
  frontend/pages/admin/[id].tsx
  frontend/pages/community/[id].tsx
  frontend/sass/components/admin/AdminMain.module.scss
  frontend/sass/components/admin/AdminSidebar.module.scss
  frontend/sass/components/admin/KeywordControl.module.scss
  frontend/sass/components/common/DefaultButton.module.scss
  frontend/sass/components/common/LoginModalContent.module.scss
  frontend/sass/components/community/keyword-bubble-chart/KeywordBubble.module.scss
  frontend/sass/components/main/CommunityItem.module.scss
  frontend/sass/components/main/MainLayout.module.scss
  frontend/utils/isEmptyInput.ts
Labels: :computer: 프론트엔드

#352 [Week07 Day03] 버그 수정 및 CD 스크립트 작성
  .github/workflows/frontend-main-cd.yml
  .github/workflows/frontend-release-cd.yml
  frontend/components/main/CommunityItem.tsx
  frontend/components/main/CommunityList.tsx
  frontend/types/types.ts
Labels: :sweat_drops: enhancement, :sparkle: feat, :computer: 프론트엔드
